### PR TITLE
Update to GitHub Apps Management

### PR DESCRIPTION
**Pull request by rfun**
Any apps installed with GitHub are now shown in the list of installed apps. Also, you may uninstall those apps from the UI as well. 
Plenty of cleanup since I switched to VSCode as an editor.

### CODE REVIEW

**Comment by rileyhales** [comment]
whats going to be the easiest way for me to review?

**Comment by rfun** [comment]
> whats going to be the easiest way for me to review?

@rileyhales : Good question. 
One option would be is to pull the branch down, install the warehouse using `tethys install -d` and try the feature locally. There is some documentation in there that tells you how to send a GitHub install request but its basically sending a POST request to `http://localhost:8000/apps/warehouse/install/git/` with the `Authorization` header value as `Token <YOUR_TETHYS_USER_TOKEN>` and body being a JSON object:
```
{
	"url":"https://github.com/rfun/tethysapp-servicetest",
	"branch":"master"
}
```

This will trigger an install that you can follow along in the logs, and then you could verify if the app you sent for install was installed and it shows up on the installed list in the warehouse. From there you can try uninstalling it to verify that part of the PR works. 

Another option is to just browse through the files changes tab on the PR to see if it makes sense logically. This will be way less work than the other option for sure.

**Review by msouff — APPROVED** [review]
This looks good to me. Feel free to merge.

**Review by rileyhales — APPROVED** [review]

**Comment by rileyhales** [comment]
@msouff and I just discussed this in our weekly meeting. I'll merge this so we can carry on with improvements and deploying this to our tethys servers.

**Pull request merged**
